#Spring开发环境
server:
#端口
   port: 8081
#日志
logging:
  path: "/var/log/"
  file: "logs.log"
  pattern:
      console: "[%d{yyyy-MM-dd HH:mm:ss,SSS}] -- %C %M%n%m%n"
spring:
#freemarker 配置
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
      datetime_format : 'yyyy-MM-dd HH:mm:ss'
      date_format : 'yyyy-MM-dd'
#数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wx?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

#mybatis配置
mybatis:
  mapper-locations: classpath:com/jiopeel/**/*.xml
  #config-location: classpath:config/mybatisConifg.xml
  type-aliases-package: com.jiopeel.*.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
