#Spring开发环境
server:
  #端口
  port: 8088
spring:
  freemarker:
    request-context-attribute: req
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    suffix: .html
  datasource:
    #数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lyc?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin123
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 100
        max-idle: 10
    timeout: 3000

#mybatis配置
mybatis:
  configuration:
    log-impl: com.jiopeel.core.config.log.LogbackImp
    cache-enabled: true
  mapper-locations: classpath*:com/jiopeel/**/dao/mapper/*.xml
  configuration-properties:
    dbType: mysql
