#Spring开发环境
server:
  #端口
  port: 8088
spring:
  freemarker:
    request-context-attribute: req
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    suffix: .html
  datasource:
    #数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lyc?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin123
#mybatis配置
mybatis:
  configuration:
    log-impl: com.jiopeel.config.log.LogbackImp
    cache-enabled: true
  mapper-locations: classpath*:com/jiopeel/dao/*.xml
